language: node_js
node_js:
  - '4'
script:
  - npm run lint
  - npm test
before_deploy:
  - NODE_ENV=production
  - npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: andrew@andrew.codes
  api_key:
    secure: TIMvUJpNSkTPdP+V6SgcweZQOownS/fGKLQDXSHR9WM6i8V2XeSfPOlD5QZUSZwo93Vchuyii7W4w2wAGOAvfj5evO86Ygn/SqGSmkgnOOEik0W4Aq0EDDxMWHGvDwG7v/6a0KiI00jpeG3EW+h3mv0dPomKNgr3XbppzRi/eUHLDIJUDkr89TYbADMzremid8PWsmln7DKE1WrMdDfF6C09WcISyxd9LQZsnKOWsAwGv48XCfAS3Aj/nML4KXLx56QcOLOCz3dGcHBqwT8aRCwUP97I/U45p5giY7IS64jt4SqMtabg028wqTc3sLV/qgP/JeyFQnXzx31fSb205/t95YyrRgqBI+lJPqTN9OGeTBXcrvnpx1UKxDomnA420MSuEKS3YqKrtKChISZdrOlATd8x2tiocCSMGoCToJP8ysYztGqGKGdOmJRfg0iE0b2wCGFjmq80ckkNkiov3uTLPGep8X7Iwx6f2AkbMR22X7uR8LVa9dIu9Z/4bQAHaZCt+fWBSLqY6heSsGbrRKT1wBsA62U4MTg2qmozzthHe6TpH3Z/hs+yzrTBi4ROFmC1jD2ZfnHpcF5nYg8nq5dJoNn0vMlYdB2fpc36Wm9uoi/OOhE8tpi1X+r5Tl571AHBDiOPtAQQduyYZnyQmfMa5FwGcK3wQePOFIB+05c=
  on:
    tags: true
    repo: andrew-codes/color-functions
