language: node_js
node_js:
  - '4'
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
script:
  - npm run lint
  - npm test
before_deploy:
  - NODE_ENV=production
  - npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: andrew@andrew.codes
  api_key:
    secure: cMzvEzenBWQ8rUtPzXY+WxWBkKogtgOHCFQBR7z7hjfNcnrxs6hq8IUv1Y591RDeoNffo8gaD05hLMaYzAZLauon6FDBlSOKTJeo4Tcfy4KkSMLIjVyEFcGnpm/0y2PVL4vFPmNiHceL5X4Y/txzTs9Whq9Pjizk9QXhb8BUBL2m8vYEiWuiMIrOzSLUrCBM+BI4s52zMElvZKw1Mo3P32s8pGOzNK9uDdsGTWyXrcttjkiaEUB8uv3TKSVuVzlXAomUx99zb9/Vx2qFTe4x+BwupnkLslejL7fBv/NtfLwerLiP2kaKXnhE6sjC1Pu2UIBXBQeXiTpHO6G/18N5XmBoaB9lEQFRJktpySz8zjhbP/PbsS94/n+rp5xl2u2CECHgFhyoe8mssLDiubfhK8GL2gT1YEZdcWp9QIF9JAJejr1rxFzAXCiJK9C+dNZIjCS9Ukqyugn7Vh/4Oo48cZurvJxgoHaFqw/u39dpK7gaSfooLpjgEQf6fnzRyCEynR4jZ6B4QvZC9y7L+39ngr6fynP2Z5r+jcm1tQEWm1TLmc4BjpaTNrriQmLQoKNjNCIpKagB3KhnY0CKjfRkISbESlp4aUCSCDymMMBBVSp+jubQjI6TQ9qq2BiqPDErUKq9NN4geGdAHfpGU2D2Pze2HkN+IP7mis+f3W84RGo=
  on:
    tags: true
    repo: andrew-codes/color-functions
